/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package parser;

/** Token Manager. */
public class ParserTokenManager implements ParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xdfc03ffffe0L) != 0L)
         {
            jjmatchedKind = 45;
            return 3;
         }
         return -1;
      case 1:
         if ((active0 & 0xdfc03dbfbe0L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 1;
            return 3;
         }
         if ((active0 & 0x240400L) != 0L)
            return 3;
         return -1;
      case 2:
         if ((active0 & 0xd7c0183fbe0L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 2;
            return 3;
         }
         if ((active0 & 0x8002580000L) != 0L)
            return 3;
         return -1;
      case 3:
         if ((active0 & 0x95c0083f3e0L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 3;
            return 3;
         }
         if ((active0 & 0x42001000800L) != 0L)
            return 3;
         return -1;
      case 4:
         if ((active0 & 0x1480002e3e0L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 4;
            return 3;
         }
         if ((active0 & 0x81400811000L) != 0L)
            return 3;
         return -1;
      case 5:
         if ((active0 & 0x80002c3e0L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 5;
            return 3;
         }
         if ((active0 & 0x14000002000L) != 0L)
            return 3;
         return -1;
      case 6:
         if ((active0 & 0x20240L) != 0L)
            return 3;
         if ((active0 & 0x80000c1a0L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 6;
            return 3;
         }
         return -1;
      case 7:
         if ((active0 & 0x800008120L) != 0L)
            return 3;
         if ((active0 & 0x4080L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 7;
            return 3;
         }
         return -1;
      case 8:
         if ((active0 & 0x4080L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 8;
            return 3;
         }
         return -1;
      case 9:
         if ((active0 & 0x80L) != 0L)
            return 3;
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 9;
            return 3;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 37:
         return jjStopAtPos(0, 48);
      case 40:
         return jjStopAtPos(0, 32);
      case 41:
         return jjStopAtPos(0, 33);
      case 44:
         return jjStopAtPos(0, 47);
      case 59:
         return jjStopAtPos(0, 31);
      case 60:
         jjmatchedKind = 29;
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 61:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 62:
         jjmatchedKind = 30;
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x8000100040L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x1800000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x5400000020L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x2200L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x40480L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0xa0000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40000000900L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 26);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 27);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 28);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000200L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x10802022120L);
      case 70:
      case 102:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(1, 10, 3);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000001000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x104080L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x400498000L);
      case 82:
      case 114:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(1, 21, 3);
         return jjMoveStringLiteralDfa2_0(active0, 0x44000000000L);
      case 83:
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(1, 18, 3);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      case 68:
      case 100:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 3);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(2, 25, 3);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 39, 3);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000000800L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x82000000020L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000008000L);
      case 82:
      case 114:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 3);
         break;
      case 84:
      case 116:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 3);
         return jjMoveStringLiteralDfa3_0(active0, 0x800000040L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x40401020000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000080L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000800000L);
      case 69:
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 3);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 3);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4200L);
      case 76:
      case 108:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 3);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000020L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
      case 78:
      case 110:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 3);
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x100L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x800020000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      case 69:
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 3);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 43, 3);
         break;
      case 72:
      case 104:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 3);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 75:
      case 107:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 23, 3);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 3);
         break;
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x8100L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 84:
      case 116:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 3);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000200L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x8340L);
      case 69:
      case 101:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 3);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x80L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000020L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 84:
      case 116:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 3);
         break;
      case 89:
      case 121:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 40, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x20L);
      case 78:
      case 110:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(6, 17, 3);
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 84:
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 6, 3);
         else if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 9, 3);
         return jjMoveStringLiteralDfa7_0(active0, 0x8180L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x80L);
      case 69:
      case 101:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(7, 8, 3);
         else if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 15, 3);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(7, 35, 3);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      case 82:
      case 114:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(7, 5, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000L);
      case 84:
      case 116:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(9, 7, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 84:
      case 116:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(10, 14, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 4;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 41)
                        kind = 41;
                     jjCheckNAdd(1);
                  }
                  else if (curChar == 45)
                     jjCheckNAdd(1);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAdd(1);
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjstateSet[jjnewStateCnt++] = 3;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 3:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(3);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
//         int i2 = (curChar & 0xff) >> 6;
//         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 4 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\75\75", "\74\75", "\76\75", "\74", "\76", "\73", "\50", "\51", null, null, null, null, 
null, null, null, null, null, null, null, null, "\75", "\54", "\45", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1efffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[4];
private final int[] jjstateSet = new int[8];
protected char curChar;
/** Constructor. */
public ParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 4; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
//private void jjAddStates(int start, int end)
//{
//   do {
//      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
//   } while (start++ != end);
//}
//private void jjCheckNAddTwoStates(int state1, int state2)
//{
//   jjCheckNAdd(state1);
//   jjCheckNAdd(state2);
//}

}
